name: Deploy Portfolio to GitHub Pages

on:
  push:
    branches:
      - main # Garante que só seja executado no branch principal

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      # 1. Configura Node.js (Ambiente necessário)
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # 2. Instala dependências e compila
      - name: Install dependencies and Build
        run: |
          npm install
          npm run build
          
      # 3. Publica o conteúdo da pasta 'dist' no GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN}}
          force_orphan: true
          publish_branch: gh-pages
          publish_dir: ./dist
          
